
[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.31.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.31"

[context.production.environment]
HUGO_VERSION = "0.31"
